const mongoose = require('mongoose')

const movieSchema = new mongoose.Schema({
    plot:{
        type:String,
        require:true
    },
    genres:{
        type:Array,
        require:true
    },
    runtime:{
        type:Number,
        require:true
    },
    cast:{
        type:Array,
        require:true
    },
    poster:{
        type:String,
        require:true
    },
    title:{
        type:String,
        require:true
    },
    fullplot:{
        type:String,
        require:true
    },
    languages:{
        type:Array,
        require:true
    },
    released:{
        type:Date,
        require:true
    },
    directors:{
        type:Array,
        require:true
    },
    rated:{
        type:String,
        require:true
    },
    awards:{
        type:Object
    },
    lastupdated:{
        type:Date,
        require:true
    },
    year:{
        type:Number,
        length:4,
        require:true
    },
    imdb:{
        type:Object,
        require:true
    },
    countries:{
        type:Array,
        require:true
    },
    type:{
        type:String,
        require:true
    },
    tomatoes:{
        type:Object,
        require:true
    },
    num_mflix_comments:{
        type:Number,
        require:true,
    }

    
},{collection:'movies'});

module.exports = mongoose.model("Movie", movieSchema)